# *********************************************************
# Thank you for using this plugin! <3
# Author: Matistan
# If you enjoy this plugin, please rate it on spigotmc.org:
# https://www.spigotmc.org/resources/shared-inventory.109491/
# *********************************************************

# Set to true to set the time to day automatically when the game starts.
timeSetDayOnStart: true
# Set to true to set the weather to clear automatically when the game starts.
weatherClearOnStart: true
# Set to true to set survival mode for all players when the game starts.
survivalOnStart: true
# Set to true to show errors in the chat when a player changed his inventory in a not implemented way. (in rare scenarios may cause item duplication or disappearance)
showSyncErrors: true
# Set to true to clear players inventories when the game starts (otherwise, they will play with the inventory of the first online player on the list).
clearInventories: true
# Set to true to take away OPs for the duration of the game.
takeAwayOps: true
# Set to true to enable permission checks.
## Note: This feature needs a permissions plugin (such as LuckPerms) to work.
usePermissions: true