name: MinecraftSharedInventory
version: '${project.version}'
main: me.matistan05.minecraftsharedinventory.Main
api-version: 1.16
authors: [Matistan]
description: Fun little plugin where every player has the same inventory!
commands:
  sharedinventory:
    description: this command sets up the whole game
permissions:
  sharedinventory.sharedinventory:
    description: Allows the player to use all /sharedinventory commands
    children:
      sharedinventory.create: true
      sharedinventory.delete: true
      sharedinventory.add: true
      sharedinventory.remove: true
      sharedinventory.start: true
      sharedinventory.reset: true
      sharedinventory.list: true
      sharedinventory.rules: true
      sharedinventory.help: true